### import numpy

In [1]:
import numpy as np

### np.array

In [13]:
#1D Array
a = np.array([1,2,3,4,5])
print(type(a))
print(f"Array : {a}")
print(f"Shape : {a.shape}")
print(f"Dimension : {a.ndim}D")

#2D Array
b = np.array([[1,2,3],[4,5,6]])
print(f"\nArray : \n{b}")
print(f"Shape : {b.shape}")
print(f"Dimension : {b.ndim}D")

#3D Array
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"\nArray : \n{c}")
print(f"Shape : {c.shape}")
print(f"Dimension : {c.ndim}D")

<class 'numpy.ndarray'>
Array : [1 2 3 4 5]
Shape : (5,)
Dimension : 1D

Array : 
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Dimension : 2D

Array : 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape : (2, 2, 3)
Dimension : 3D


In [49]:
#np.reshape - transforms one array to mentioned dimension
a = np.array([1,2,3,4,5,6])
print("Original : ",a)

b = a.reshape(3,2)
print("After reshaping : \n",b)

Original :  [1 2 3 4 5 6]
After reshaping : 
 [[1 2]
 [3 4]
 [5 6]]


In [50]:
#np.random - creates array using random numbers
a = np.random.random((3,4))
print(a)

[[0.34723859 0.96641824 0.89339339 0.81227721]
 [0.96216301 0.35410059 0.69772679 0.55074726]
 [0.08261539 0.71531002 0.19705157 0.57689701]]


### different data type of array values

In [20]:
a = np.array([1,2,3,4,5])
print(f"Array : {a}")

b = np.array([1,2,3,4,5],dtype='float32')
print(f"Array : {b}")

Array : [1 2 3 4 5]
Array : [1. 2. 3. 4. 5.]


### Intrinsic func to create numpy array

In [24]:
#1D Arrays

#np.arange - creates arrays with regularly incrementing values
a = np.arange(10)
print("Arange : ",a)

#np.linspace - creates array of equally spaced values between specified range
b = np.linspace(-10, 10, 7)
print("Linspace : ",b)

Arange :  [0 1 2 3 4 5 6 7 8 9]
Linspace :  [-10.          -6.66666667  -3.33333333   0.           3.33333333
   6.66666667  10.        ]


In [34]:
#2D Arrays

#np.eye - creates a 2d identity matrix
a = np.eye(4)
print("np.eye : \n",a)

#np.diag - creates a 2d array with the values set as diagonal
b = np.diag([1,2,3,4])
print("\nnp.diag : \n",b)

#it also return the diagonal values
x = np.diag(b)
print("\nDiagonal elements : ",x)

np.eye : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.diag : 
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

Diagonal elements :  [1 2 3 4]


In [37]:
#np.zeros - creates a matrix with all values set to 0
a = np.zeros((3,4))
print("np.zeros : \n",a)

b = np.ones((3,4))
print("\nnp.ones : \n",b)

np.zeros : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### np.block - joins arrays of same dimension

In [42]:
A = np.ones((2, 2))
B = np.zeros((2, 2))
C = np.eye(2, 2)
D = np.diag((-3, -4))

np.block([[A, B], [C, D]])

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  0., -3.,  0.],
       [ 0.,  1.,  0., -4.]])

### indexing

In [45]:
a = np.array([1,2,3,4,5])
print(a[:3])  #elements 0,1,2

[1 2 3]


In [47]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(b[:, :2])  #all rows, 0,1 column

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [60]:
c = np.random.random((4,3))
print(c)

x = np.random.random()
print("\nx : ",x)

d = c > x
print("\n",d)

[[0.75930369 0.65699482 0.62049961]
 [0.4258525  0.11670256 0.13211086]
 [0.5849072  0.9448735  0.42553401]
 [0.22540136 0.4456379  0.48448439]]

x :  0.3752034071719842

 [[ True  True  True]
 [ True False False]
 [ True  True  True]
 [False  True  True]]


### view and copy

In [67]:
#np.view - creates a view
a = np.arange(8)
print(a)

b = a[:3]  #creates a view
print(b)

a[:3] = [11,12,12]  #updating values of a
print(b)  #values get updated in b also

[0 1 2 3 4 5 6 7]
[0 1 2]
[11 12 12]


In [77]:
#np.copy - creates a copy of array
a = np.array([1,2,3,4,5,6,7,8,9,10])
print("a : ",a)

b = a[::2].copy()
print("b : ",b)

a[::2] = a[::2]*10  #updating values of a
print("\nAfter updating :\na :",a)
print("b : ",b)  #values of b remains same as it was a copy

a :  [ 1  2  3  4  5  6  7  8  9 10]
b :  [1 3 5 7 9]

After updating :
a : [10  2 30  4 50  6 70  8 90 10]
b :  [1 3 5 7 9]


### transpose

In [81]:
a = np.array([1,2,3,4,5,6]).reshape(3,2)
print("a :\n",a)

print("\na transpose : \n",a.T)

a :
 [[1 2]
 [3 4]
 [5 6]]

a transpose : 
 [[1 3 5]
 [2 4 6]]
