In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [3]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

## **Training Testing data**

In [13]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## **Scaling**

In [14]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [15]:
x_train

array([[-0.41193051, -0.49006408, -0.44029224, ..., -0.86661735,
        -0.33038694, -0.79737577],
       [-0.17738588,  0.33111883, -0.14059777, ...,  1.71037656,
        -0.13984338,  1.30921824],
       [-1.1329381 , -0.43640724, -1.11638619, ..., -0.87071553,
         0.2572558 ,  0.25481888],
       ...,
       [ 2.10725262, -1.0033034 ,  2.07672213, ...,  1.26716639,
        -0.26313627,  0.18261485],
       [ 1.86981237,  0.34045046,  1.93001855, ...,  1.54341382,
         0.29248234, -0.42202503],
       [ 2.72691375,  1.1359714 ,  2.65515341, ...,  1.45386109,
        -0.48250154, -0.32887632]])

In [16]:
y_train

325    B
39     M
222    B
409    B
392    M
      ..
556    B
362    B
372    M
535    M
339    M
Name: diagnosis, Length: 455, dtype: object

## **Label Encoding**

In [17]:
en = LabelEncoder()
y_train = en.fit_transform(y_train)
y_test = en.transform(y_test)

In [18]:
y_train

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,

## **Arrays to Tensors**

In [20]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [23]:
x_train_tensor

tensor([[-0.4119, -0.4901, -0.4403,  ..., -0.8666, -0.3304, -0.7974],
        [-0.1774,  0.3311, -0.1406,  ...,  1.7104, -0.1398,  1.3092],
        [-1.1329, -0.4364, -1.1164,  ..., -0.8707,  0.2573,  0.2548],
        ...,
        [ 2.1073, -1.0033,  2.0767,  ...,  1.2672, -0.2631,  0.1826],
        [ 1.8698,  0.3405,  1.9300,  ...,  1.5434,  0.2925, -0.4220],
        [ 2.7269,  1.1360,  2.6552,  ...,  1.4539, -0.4825, -0.3289]],
       dtype=torch.float64)

In [22]:
x_train_tensor.shape

torch.Size([455, 30])

In [24]:
y_train_tensor.shape

torch.Size([455])

## **Defining Model**

In [36]:
class BreastCancer():
  def __init__(self,x):

    #randomly initializing the weights
    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)

    #only one neuron so only one bias and its value=0
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)


  def forward(self, x):
    z = torch.matmul(x, self.weights) + self.bias
    y_pred = torch.sigmoid(z)   #using sigmoid activation function
    return y_pred

  def loss_func(self,y,y_pred):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    #calculate loss - log loss
    loss = -(y_train_tensor * torch.tensor(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


## **Parameters**

In [39]:
lr = 0.1
epochs = 50

## **training pipeline**

In [41]:
#create model
model = BreastCancer(x_train_tensor)

for epoch in range(epochs):
  #forward pass
  y_pred = model.forward(x_train_tensor)

  #loss calculation
  loss = model.loss_func(y_train_tensor,y_pred)

  #backward pass
  loss.backward()

  #parameter update
  with torch.no_grad():
    model.weights -= lr * model.weights.grad
    model.bias -= lr * model.bias.grad

  #make gradients zero
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  if epoch % 5 == 0:
    print(f"epoch : {epoch}, loss : {loss:.8f}")

/tmp/ipython-input-1559078876.py:21: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  loss = -(y_train_tensor * torch.tensor(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()


epoch : 0, loss : 2.17325787
epoch : 5, loss : 1.96385048
epoch : 10, loss : 1.69605170
epoch : 15, loss : 1.37659970
epoch : 20, loss : 1.01565891
epoch : 25, loss : 0.66647495
epoch : 30, loss : 0.40547520
epoch : 35, loss : 0.26874656
epoch : 40, loss : 0.20454913
epoch : 45, loss : 0.16837369


## **Model Evaluation**

In [44]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"accuracy : {accuracy:.2f}")

accuracy : 0.60
