## **Import Libraries**

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

## **Load Dataset**

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## **Training Testing data**

In [4]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

## **Scaling**

In [5]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [6]:
x_train

array([[ 1.58917624,  0.90626094,  1.57275874, ...,  1.07537726,
        -0.50306254, -0.43029431],
       [ 0.1800095 ,  0.53156667,  0.16336494, ...,  1.08937826,
         1.24365721,  1.41891876],
       [ 0.04608043,  0.66109062,  0.20013174, ...,  1.01315057,
        -0.08584249,  1.62943433],
       ...,
       [ 0.22659353,  0.21238267,  0.18745353, ..., -0.18160178,
        -0.82531832, -0.98594461],
       [ 0.58761971, -0.28720969,  0.56695447, ...,  0.12797598,
        -0.16679564, -0.12227679],
       [ 0.26444304, -0.87469329,  0.24366024, ...,  0.38154972,
         0.08540454, -0.00926317]])

In [7]:
y_train

389    M
57     M
62     M
532    B
438    B
      ..
368    M
321    M
495    B
141    M
227    B
Name: diagnosis, Length: 455, dtype: object

## **Label Encoding**

In [8]:
en = LabelEncoder()
y_train = en.fit_transform(y_train)
y_test = en.transform(y_test)

In [9]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,

## **Arrays to Tensors**

In [10]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float()
y_test_tensor = torch.from_numpy(y_test).float()

In [11]:
x_train_tensor

tensor([[ 1.5892,  0.9063,  1.5728,  ...,  1.0754, -0.5031, -0.4303],
        [ 0.1800,  0.5316,  0.1634,  ...,  1.0894,  1.2437,  1.4189],
        [ 0.0461,  0.6611,  0.2001,  ...,  1.0132, -0.0858,  1.6294],
        ...,
        [ 0.2266,  0.2124,  0.1875,  ..., -0.1816, -0.8253, -0.9859],
        [ 0.5876, -0.2872,  0.5670,  ...,  0.1280, -0.1668, -0.1223],
        [ 0.2644, -0.8747,  0.2437,  ...,  0.3815,  0.0854, -0.0093]])

In [12]:
x_train_tensor.shape

torch.Size([455, 30])

In [13]:
y_train_tensor.shape

torch.Size([455])

## **Training Pipeline**
**Batch Gradient Descent - taking complete training dataset at a time**

**Defining Model**

In [14]:
class BreastCancer(nn.Module):

  def __init__(self, num_of_features):
    super().__init__()
    self.linear = nn.Linear(num_of_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features) :
    out = self.linear(features)
    out = self.sigmoid(out)
    return out


**Parameters**

In [15]:
lr = 0.1
epochs = 50

**Training**

In [16]:
loss_func = nn.BCELoss()  #binary cross entropy loss

#create model
model = BreastCancer(x_train_tensor.shape[1])

#optimization
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

for epoch in range(epochs):
  #forward pass
  y_pred = model(x_train_tensor)

  #loss calculation
  loss = loss_func(y_pred, y_train_tensor.view(-1,1))

  #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parametre updation
  optimizer.step()

  if epoch % 5 == 0:
    print(f"epoch : {epoch}, loss : {loss:.8f}")

epoch : 0, loss : 0.69703680
epoch : 5, loss : 0.33866030
epoch : 10, loss : 0.25638098
epoch : 15, loss : 0.21624921
epoch : 20, loss : 0.19155158
epoch : 25, loss : 0.17454953
epoch : 30, loss : 0.16202872
epoch : 35, loss : 0.15236814
epoch : 40, loss : 0.14465113
epoch : 45, loss : 0.13831837


**Model Evaluation**

In [17]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"accuracy : {accuracy:.4f}")

accuracy : 0.5098


## **Training Pipeline**
**Mini Batch Gradient Descent - creating batches and then using them in training**

**Create Custom Dataset**

In [18]:
class CustomDataset(Dataset) :

  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [19]:
#creating objects of custom dataset class
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [20]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

**Define model**

In [21]:
class Cancer(nn.Module):
  def __init__(self, num_of_features):
    super().__init__()
    self.linear = nn.Linear(num_of_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features) :
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

**define paramaters**

In [22]:
lr = 0.1
epochs = 50

In [23]:
#create model
model = Cancer(x_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=lr)

#loss function
loss_func = nn.BCELoss()

**Training**

In [24]:
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:

    #forward pass
    y_pred = model(batch_features)

    #calculate loss
    loss = loss_func(y_pred, batch_labels.view(-1,1))

    #clear gradients
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameters update
    optimizer.step()

  if epoch % 5 == 0:
    print(f"epoch : {epoch}, loss : {loss:.8f}")

epoch : 0, loss : 0.24883297
epoch : 5, loss : 0.11275493
epoch : 10, loss : 0.03101851
epoch : 15, loss : 0.06888487
epoch : 20, loss : 0.05177720
epoch : 25, loss : 0.04451746
epoch : 30, loss : 0.01296242
epoch : 35, loss : 0.07209922
epoch : 40, loss : 0.31668052
epoch : 45, loss : 0.01487810


**Evaluation**

In [25]:
#model evaluation
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader :
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1)  == batch_labels).float().mean()
    accuracy_list.append(batch_accuracy.item())

overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"overall accuracy : {overall_accuracy:.4f}")

overall accuracy : 0.9922
