In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Cross Attetion
### Q is taken from output seq
### K,V are taken from output of Encoder block

In [2]:
import numpy as np

In [8]:
seq_len = 5
d_model = 6

x = np.random.rand(seq_len, d_model)
print(x)
print("Shape : ", x.shape)

[[0.31110671 0.00106925 0.8323345  0.60261358 0.71171955 0.71329374]
 [0.51131938 0.21798918 0.06035592 0.68215819 0.00717535 0.32685803]
 [0.65768351 0.41783417 0.22859819 0.29967584 0.79057474 0.21956969]
 [0.67312432 0.66922767 0.87647125 0.43534223 0.34968947 0.23603022]
 [0.70003422 0.94433214 0.60945899 0.14688352 0.30429529 0.1542338 ]]
Shape :  (5, 6)


## Create Q,K,V matrix for encoder output and Decoder input

In [13]:
d_q = 3
d_kv = 4

#input to decoder
x_q = np.random.rand(d_q, d_model)
print("Decoder input : \n",x_q)
print("Shape : ", x_q.shape)

#output form encoder
x_kv = np.random.rand(d_kv, d_model)
print("\nEncoer Output : \n",x_kv)
print(x_kv.shape)

Decoder input : 
 [[0.30354963 0.58238147 0.90548989 0.91383387 0.81541462 0.3522402 ]
 [0.65431534 0.6288405  0.45928851 0.93774951 0.66452541 0.81441435]
 [0.149132   0.45137021 0.00519644 0.00887336 0.88131417 0.25078827]]
Shape :  (3, 6)

Encoer Output : 
 [[0.19678757 0.75259519 0.53630486 0.67578783 0.16382039 0.03247859]
 [0.43310298 0.20543136 0.55048074 0.40229292 0.24161152 0.92259053]
 [0.77276471 0.77106604 0.8200619  0.08173411 0.31224846 0.90498076]
 [0.73069832 0.62153831 0.85125858 0.75260132 0.7537301  0.17667466]]
(4, 6)


## Compute Q,K,V  matrix

In [14]:
w_q = np.random.rand(d_model, d_model)
w_k = np.random.rand(d_model, d_model)
w_v = np.random.rand(d_model, d_model)

In [17]:
Q = x_q @ w_q
K = x_kv @ w_k
V = x_kv @ w_v

print("Q : \n", Q)
print("Shape : ",Q.shape)

print("\nK : \n", K)
print("Shape : ",K.shape)

print("\nV : \n", V)
print("Shape : ",V.shape)

Q : 
 [[0.83803779 2.22000256 2.10108379 1.97118737 2.80745655 2.4984668 ]
 [0.69961718 2.20674208 2.3288336  1.89718594 2.65710852 2.45383014]
 [0.12331906 1.23354348 0.88908312 1.07872233 1.32623439 1.01686668]]
Shape :  (3, 6)

K : 
 [[1.29106547 0.89487478 1.3189154  1.73258359 1.04426629 0.98864326]
 [0.75896183 1.31305419 1.00912442 2.08734146 1.27223937 1.40629382]
 [1.20416757 2.01557214 1.42297302 2.45662211 1.47954629 1.59987654]
 [1.56318599 1.41837813 1.91494631 2.78978228 1.83532031 1.46532521]]
Shape :  (4, 6)

V : 
 [[0.89328571 1.2737677  0.9371142  1.35179049 1.09217443 1.44897002]
 [0.67292307 1.18056227 1.16187772 1.40006401 1.39849642 1.93127786]
 [1.13933665 1.40715483 1.77040793 1.73941796 1.61874081 2.38082225]
 [1.13964357 2.03558138 1.85223603 2.40930094 2.25548096 2.40620115]]
Shape :  (4, 6)


## Scaled Dot Product

In [19]:
d_k = d_model 

score = Q @ K.T
score = score / d_k

print("Scaled dot product : \n",score)
print("Shape : ",score.shape)

Scaled dot product : 
 [[2.44280153 2.81185894 3.57782693 3.79918445]
 [2.40621143 2.7616661  3.52033013 3.74137632]
 [1.1158237  1.32991036 1.6898389  1.76307565]]
Shape :  (3, 4)


## Softmax

In [20]:
def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

## Final Attention output

In [21]:
attention_weights = softmax(score)
print("Attention weights : \n", attention_weights)
print("Shape : ",attention_weights.shape)

Attention weights : 
 [[0.10593502 0.1532213  0.3295906  0.41125308]
 [0.10782446 0.15384709 0.32852838 0.40980007]
 [0.1687936  0.20908969 0.29967299 0.32244372]]
Shape :  (3, 4)


In [23]:
attention_output = attention_weights @ V
print("Attention Output : \n",attention_output)
print("Shape : ",attention_output.shape)

Attention Output : 
 [[1.04193297 1.61674801 1.62254521 1.92184982 1.79107421 2.22366384]
 [1.04117574 1.61544107 1.62047104 1.91993171 1.78901627 2.22158497]
 [1.00038152 1.53989396 1.52890085 1.81903307 1.68912181 2.13771973]]
Shape :  (3, 6)
